-- begin DDCDI_IMPORT_LOG
alter table DDCDI_IMPORT_LOG add constraint FK_DDCDI_IMPORT_LOG_FILE foreign key (FILE_ID) references SYS_FILE(ID)^
alter table DDCDI_IMPORT_LOG add constraint FK_DDCDI_IMPORT_LOG_SCENARIO foreign key (SCENARIO_ID) references DDCDI_IMPORT_SCENARIO(ID)^
create index IDX_DDCDI_IMPORT_LOG_FILE on DDCDI_IMPORT_LOG (FILE_ID)^
create index IDX_DDCDI_IMPORT_LOG_SCENARIO on DDCDI_IMPORT_LOG (SCENARIO_ID)^
-- end DDCDI_IMPORT_LOG
-- begin DDCDI_IMPORT_LOG_RECORD
alter table DDCDI_IMPORT_LOG_RECORD add constraint FK_DDCDI_IMPORT_LOG_RECORD_IMPORT_LOG foreign key (IMPORT_LOG_ID) references DDCDI_IMPORT_LOG(ID)^
create index IDX_DDCDI_IMPORT_LOG_RECORD_IMPORT_LOG on DDCDI_IMPORT_LOG_RECORD (IMPORT_LOG_ID)^
-- end DDCDI_IMPORT_LOG_RECORD
-- begin DDCDI_IMPORT_SCENARIO
alter table DDCDI_IMPORT_SCENARIO add constraint FK_DDCDI_IMPORT_SCENARIO_TEMPLATE foreign key (TEMPLATE_ID) references SYS_FILE(ID)^
create index IDX_DDCDI_IMPORT_SCENARIO_TEMPLATE on DDCDI_IMPORT_SCENARIO (TEMPLATE_ID)^
-- end DDCDI_IMPORT_SCENARIO
-- begin DDCDI_IMPORT_ATTRIBUTE_MAPPER
alter table DDCDI_IMPORT_ATTRIBUTE_MAPPER add constraint FK_DDCDI_IMPORT_ATTRIBUTE_MAPPER_IMPORT_SCENARIO foreign key (IMPORT_SCENARIO_ID) references DDCDI_IMPORT_SCENARIO(ID)^
create index IDX_DDCDI_IMPORT_ATTRIBUTE_MAPPER_IMPORT_SCENARIO on DDCDI_IMPORT_ATTRIBUTE_MAPPER (IMPORT_SCENARIO_ID)^
-- end DDCDI_IMPORT_ATTRIBUTE_MAPPER
