-- begin DDCDI_IMPORT_LOG
alter table DDCDI_IMPORT_LOG add constraint FK_DDCDI_IMPORT_LOG_FILE foreign key (FILE_ID) references SYS_FILE(ID)^
alter table DDCDI_IMPORT_LOG add constraint FK_DDCDI_IMPORT_LOG_CONFIGURATION foreign key (CONFIGURATION_ID) references DDCDI_IMPORT_CONFIGURATION(ID)^
create index IDX_DDCDI_IMPORT_LOG_FILE on DDCDI_IMPORT_LOG (FILE_ID)^
create index IDX_DDCDI_IMPORT_LOG_CONFIGURATION on DDCDI_IMPORT_LOG (CONFIGURATION_ID)^
-- end DDCDI_IMPORT_LOG
-- begin DDCDI_IMPORT_LOG_RECORD
alter table DDCDI_IMPORT_LOG_RECORD add constraint FK_DDCDI_IMPORT_LOG_RECORD_IMPORT_LOG foreign key (IMPORT_LOG_ID) references DDCDI_IMPORT_LOG(ID)^
create index IDX_DDCDI_IMPORT_LOG_RECORD_IMPORT_LOG on DDCDI_IMPORT_LOG_RECORD (IMPORT_LOG_ID)^
-- end DDCDI_IMPORT_LOG_RECORD
-- begin DDCDI_IMPORT_CONFIGURATION
alter table DDCDI_IMPORT_CONFIGURATION add constraint FK_DDCDI_IMPORT_CONFIGURATION_TEMPLATE foreign key (TEMPLATE_ID) references SYS_FILE(ID)^
create index IDX_DDCDI_IMPORT_CONFIGURATION_TEMPLATE on DDCDI_IMPORT_CONFIGURATION (TEMPLATE_ID)^
-- end DDCDI_IMPORT_CONFIGURATION
-- begin DDCDI_IMPORT_ATTRIBUTE_MAPPER
alter table DDCDI_IMPORT_ATTRIBUTE_MAPPER add constraint FK_DDCDI_IMPORT_ATTRIBUTE_MAPPER_CONFIGURATION foreign key (CONFIGURATION_ID) references DDCDI_IMPORT_CONFIGURATION(ID)^
create index IDX_DDCDI_IMPORT_ATTRIBUTE_MAPPER_CONFIGURATION on DDCDI_IMPORT_ATTRIBUTE_MAPPER (CONFIGURATION_ID)^
-- end DDCDI_IMPORT_ATTRIBUTE_MAPPER
-- begin DDCDI_MLB_PLAYER
alter table DDCDI_MLB_PLAYER add constraint FK_DDCDI_MLB_PLAYER_TEAM foreign key (TEAM_ID) references DDCDI_MLB_TEAM(ID)^
create index IDX_DDCDI_MLB_PLAYER_TEAM on DDCDI_MLB_PLAYER (TEAM_ID)^
-- end DDCDI_MLB_PLAYER
-- begin DDCDI_MLB_TEAM
create unique index IDX_DDCDI_MLB_TEAM_CODE_UNQ on DDCDI_MLB_TEAM (CODE, DELETE_TS) ^
-- end DDCDI_MLB_TEAM
