alter table DDCDI_IMPORT_LOG_RECORD add constraint FK_DDCDI_IMPORT_LOG_RECORD_IMPORT_LOG foreign key (IMPORT_LOG_ID) references DDCDI_IMPORT_LOG(ID);
create index IDX_DDCDI_IMPORT_LOG_RECORD_IMPORT_LOG on DDCDI_IMPORT_LOG_RECORD (IMPORT_LOG_ID);
