alter table DDCDI_IMPORT_SCENARIO add constraint FK_DDCDI_IMPORT_SCENARIO_TEMPLATE foreign key (TEMPLATE_ID) references SYS_FILE(ID);
create index IDX_DDCDI_IMPORT_SCENARIO_TEMPLATE on DDCDI_IMPORT_SCENARIO (TEMPLATE_ID);
