alter table DDCDI_IMPORT_LOG add constraint FK_DDCDI_IMPORT_LOG_FILE foreign key (FILE_ID) references SYS_FILE(ID);
alter table DDCDI_IMPORT_LOG add constraint FK_DDCDI_IMPORT_LOG_SCENARIO foreign key (SCENARIO_ID) references DDCDI_IMPORT_SCENARIO(ID);
create index IDX_DDCDI_IMPORT_LOG_FILE on DDCDI_IMPORT_LOG (FILE_ID);
create index IDX_DDCDI_IMPORT_LOG_SCENARIO on DDCDI_IMPORT_LOG (SCENARIO_ID);
