alter table DDCDI_IMPORT_CONFIGURATION add column TRANSACTION_STRATEGY varchar(50) ^
update DDCDI_IMPORT_CONFIGURATION set TRANSACTION_STRATEGY = 'SINGLE_TRANSACTION' where TRANSACTION_STRATEGY is null ;
alter table DDCDI_IMPORT_CONFIGURATION alter column TRANSACTION_STRATEGY set not null ;
