alter table DDCDI_IMPORT_ATTRIBUTE_MAPPER alter column DYNAMIC_ENTITY_ATTRIBUTE rename to DYNAMIC_ENTITY_ATTRIBUTE__U73529 ;
update DDCDI_IMPORT_ATTRIBUTE_MAPPER set ATTRIBUTE_TYPE = 'DIRECT_ATTRIBUTE' where ATTRIBUTE_TYPE is null ;
alter table DDCDI_IMPORT_ATTRIBUTE_MAPPER alter column ATTRIBUTE_TYPE set not null ;
