alter table DDCDI_IMPORT_ATTRIBUTE_MAPPER add column ATTRIBUTE_TYPE varchar(50) ^
update DDCDI_IMPORT_ATTRIBUTE_MAPPER set ATTRIBUTE_TYPE = 'DIRECT_ATTRIBUTE' where ATTRIBUTE_TYPE is null ;
alter table DDCDI_IMPORT_ATTRIBUTE_MAPPER alter column ATTRIBUTE_TYPE set not null ;
alter table DDCDI_IMPORT_ATTRIBUTE_MAPPER add column ASSOCIATION_LOOKUP_ATTRIBUTE varchar(255) ;
