alter table DDCDI_IMPORT_ATTRIBUTE_MAPPER add column ASSOCIATION_LOOKUP_ATTRIBUTE varchar(255) ;
alter table DDCDI_IMPORT_ATTRIBUTE_MAPPER add column ATTRIBUTE_TYPE varchar(50) ;
alter table DDCDI_IMPORT_ATTRIBUTE_MAPPER add column MAPPER_MODE varchar(50) ^
update DDCDI_IMPORT_ATTRIBUTE_MAPPER set MAPPER_MODE = 'AUTOMATIC' where MAPPER_MODE is null ;
alter table DDCDI_IMPORT_ATTRIBUTE_MAPPER modify column MAPPER_MODE varchar(50) not null ;
alter table DDCDI_IMPORT_ATTRIBUTE_MAPPER modify column ENTITY_ATTRIBUTE varchar(255) null ;
