update DDCDI_UNIQUE_CONFIGURATION_ATTRIBUTE set ENTITY_ATTRIBUTE = '' where ENTITY_ATTRIBUTE is null ;
alter table DDCDI_UNIQUE_CONFIGURATION_ATTRIBUTE modify column ENTITY_ATTRIBUTE varchar(255) not null ;
