alter table DDCDI_IMPORT_EXEC add constraint FK_DDCDI_IMPORT_EXEC_FILE foreign key (FILE_ID) references SYS_FILE(ID);
alter table DDCDI_IMPORT_EXEC add constraint FK_DDCDI_IMPORT_EXEC_CONFIGURATION foreign key (CONFIGURATION_ID) references DDCDI_IMPORT_CONFIGURATION(ID);
create index IDX_DDCDI_IMPORT_EXEC_FILE on DDCDI_IMPORT_EXEC (FILE_ID);
create index IDX_DDCDI_IMPORT_EXEC_CONFIGURATION on DDCDI_IMPORT_EXEC (CONFIGURATION_ID);
